### PR TITLE
#58 Expose badges on glific repository

### PR DESCRIPTION
**Pull request by Satendra-SR**
### Changes:

- Badge for Continuous integration.
- Badge for Code coverage.

### CODE REVIEW

**Comment by Satendra-SR** [comment]
FYI, as the base commit is not available on the master branch, it is not showing the coverage diff right now. Once merged to master, it will start showing it while creating a new pull request.

**Comment by pankaj-ag** [comment]
@Satendra-SR I checked this one your branch and code coverage is not coming up there. 
Let me know in case I am missing something here. 

image

**Comment by Satendra-SR** [comment]
That's correct @pankaj-ag  If you see, the badges are getting picked from the master branch. So as soon as it will merge, the badge will show correctly.

image


For the Continuous Integration badge, the changes are already in the master branch, so it is showing fine.

**Comment by pankaj-ag** [comment]
Okay, I can not wait to see the badges. Merging this.

**Pull request merged**
