### PR TITLE
attempt to move to  oban vanilla - 01

### PR DESCRIPTION
**Pull request by TwistingTwists**
## Summary
Target issue is - ___________ 
Explain the **motivation** for making this change. What existing problem does the pull request solve?
1. Easy for other users to contribute to the project by incuding Oban Vanilla. as mentioned in discord channel

## Checklist
 Before submitting a pull request, please ensure that you mark these task.

- [x] Ran `mix setup` in the repository root and test.
- [ ] If you've fixed a bug or added code that is tested and has test cases. 
- [ ] In the case of adding a new API, you added a **postman** request for that.
- [ ] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing

### CODE REVIEW

**Review by siddhant3030 — COMMENTED** [review]
@TwistingTwists We need a way to still use the oban pro but the key which we need to start the project can be optional. That way anyone can use the project. From what I you have removed all the dependency for the oban.

**Comment by pankaj-ag** [comment]
@siddhant3030 right now that's not possible. I think we need to manage two different branches like master and master-without-oban or something like that. 

We need to figure out a way to keep this branch sync with master.

**Comment by pankaj-ag** [comment]
@TwistingTwists this looks fine, I will test it today.

**Comment by pankaj-ag** [comment]
@TwistingTwists can you try to fix the checks?

**Comment by TwistingTwists** [comment]
@pankaj-ag  : updated mix.lock. 

I ran `mix deps.clean --all` and `mix deps.get`

**Pull request closed without merging**
